export const Media = [
    { label: "VINYL", value: 0 },
    { label: "CD", value: 1 },
    { label: "UNSPECIFIED", value: 2 }
];

export const Category = [
    { label: "NEW", value: false },
    { label: "USED", value: true },
];

export const ArtistGenre = [
    { label: "ROCK", value: 0 },
    { label: "POP", value: 1 },
    { label: "JAZZ", value: 2 },
    { label: "HIPHOP", value: 3 },
    { label: "ALTERNATIVE", value: 4 },
    { label: "CLASSICAL", value: 5 },
    { label: "FRANCOPHONE", value: 6 },
    { label: "METAL", value: 7 },
    { label: "PUNK", value: 8 },
    { label: "BLUES", value: 9 },
    { label: "WORLD", value: 10 },
    { label: "FOLK", value: 11 },
    { label: "COUNTRY", value: 12 },
    { label: "SOUL", value: 13 },
    { label: "FUNK", value: 14 },
    { label: "ELECTRONICA", value: 15 },
    { label: "SOUNDTRACK", value: 16 },
    { label: "UNSPECIFIED", value: 17 }
];

export const AlbumGenre = [
    { label: "ROCK", value: 0 },
    { label: "POP", value: 1 },
    { label: "JAZZ", value: 2 },
    { label: "HIPHOP", value: 3 },
    { label: "ALTERNATIVE", value: 4 },
    { label: "CLASSICAL", value: 5 },
    { label: "FRANCOPHONE", value: 6 },
    { label: "METAL", value: 7 },
    { label: "PUNK", value: 8 },
    { label: "BLUES", value: 9 },
    { label: "WORLD", value: 10 },
    { label: "FOLK", value: 11 },
    { label: "COUNTRY", value: 12 },
    { label: "SOUL", value: 13 },
    { label: "FUNK", value: 14 },
    { label: "ELECTRONICA", value: 15 },
    { label: "SOUNDTRACK", value: 16 },
    { label: "HARD", value: 17 },
    { label: "FUSION", value: 18 },
    { label: "PROG", value: 19 },
    { label: "MODAL", value: 20 },
    { label: "FREEJAZZ", value: 21 },
    { label: "INDIE", value: 22 },
    { label: "POSTBOP", value: 23 },
    { label: "MINIMALIST", value: 24 },
    { label: "PSYCH", value: 25 },
    { label: "HARDROCK", value: 26 },
    { label: "RAP", value: 27 },
    { label: "GARAGE", value: 28 },
    { label: "VAPORWAVE", value: 29 },
    { label: "ROCKABILLY", value: 30 },
    { label: "EXPERIMENTAL", value: 31 },
    { label: "INSTRUMENTAL", value: 32 },
    { label: "INDUSTRIAL", value: 33 },
    { label: "SYNTHWAVE", value: 34 },
    { label: "KITSCH", value: 35 },
    { label: "REGGAE", value: 36 },
    { label: "NEWWAVE", value: 37 },
    { label: "DOWNTEMPO", value: 38 },
    { label: "ACOUSTIC", value: 39 },
    { label: "NEWAGE", value: 40 },
    { label: "OPERA", value: 41 },
    { label: "STONER", value: 42 },
    { label: "DOOM", value: 43 },
    { label: "IDM", value: 44 },
    { label: "TRIPHOP", value: 45 },
    { label: "DEATHCORE", value: 46 },
    { label: "DEATHMETAL", value: 47 },
    { label: "METALCORE", value: 48 },
    { label: "HARDCORE", value: 49 },
    { label: "MODERN", value: 50 },
    { label: "HOUSE", value: 51 },
    { label: "BAROQUE", value: 52 },
    { label: "ROMANTIC", value: 53 },
    { label: "AFROBEAT", value: 54 },
    { label: "DANCE", value: 55 },
    { label: "NOISE", value: 56 },
    { label: "AMBIENT", value: 57 },
    { label: "VARIETY", value: 58 },
    { label: "GRUNGE", value: 59 },
    { label: "HISTORICAL", value: 60 },
    { label: "MUSICAL", value: 61 },
    { label: "DISCO", value: 62 },
    { label: "COMEDY", value: 63 },
    { label: "SOUNDEFFECTS", value: 64 },
    { label: "KIDS", value: 65 },
    { label: "CHRISTMAS", value: 66 },
    { label: "UNSPECIFIED", value: 67 }
];

export const FormatType = {
    RPM_33: "RPM_33",
    RPM_45: "RPM_45",
    RPM_78: "RPM_78",
    LP: "LP",
    EP: "EP",
    ALBUM: "ALBUM",
    SINGLE: "SINGLE",
    DOUBLE: "DOUBLE",
    FLEXIDISC: "FLEXIDISC",
    PICTUREDISC: "PICTUREDISC",
    SHELLAC: "SHELLAC",
    DIGIPAK: "DIGIPAK",
    INCH_12: "INCH_12",
    INCH_10: "INCH_10",
    INCH_7: "INCH_7",
    INCH_5: "INCH_5",
    INCH_3: "INCH_3",
    UNSPECIFIED: "UNSPECIFIED"
};

export const Grade = [
    { label: "M", value: 0 },
    { label: "NM", value: 1 },
    { label: "VG_PLUS", value: 2 },
    { label: "VG", value: 3 },
    { label: "G_PLUS", value: 4 },
    { label: "G", value: 5 },
    { label: "F", value: 6 },
    { label: "P", value: 7 },
    { label: "NONE", value: 8 }
];
